#!/usr/bin/env bash

source ./recarm_lib

register_install_step "Python" "curl https://pyenv.run | bash"
register_install_step "Python" "export PYENV_ROOT=\"$HOME/.pyenv\""
register_install_step "Python" "command -v pyenv >/dev/null || export PATH=\"$PYENV_ROOT/bin:$PATH\""
register_install_step "Python" "pyenv init"
register_install_step "Python" "pyenv virtualenv-init"

register_install_step "Python" "pyenv install 3:latest"

# Runs only if this script is run directly.
# If it is sourced, we only want to register the steps.
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    run_installer "Python"
fi