#!/usr/bin/env bash

# Allow passing in the path of the recarm_lib and color_lib files.
SCRIPT_DIR="."
if [[ -n $1 ]]; then
    SCRIPT_DIR=$1
fi

cd "$SCRIPT_DIR" || exit
source "recarm_lib"
cd - || exit

register_install_step "Rust" \
    "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"

register_install_step "Rust" \
    "source \"$HOME/.cargo/env\""


# Runs only if this script is run directly.
# If it is sourced, we only want to register the steps.
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    run_installer "Rust"
fi